server:
  port: 8080

spring:
  application:
    name: backendvault

  datasource:
    url: jdbc:clickhouse://localhost:8123/trading_db?autoCommit=true&compress=true&tcpKeepAlive=true&tcpNoDelay=true&maxExecutionTime=60&maxThreads=4&maxInsertBlockSize=1048576&minInsertBlockSizeRows=500&socketTimeout=300000
    username: ${DB_USERNAME:default}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 250
      validation-timeout: 250
      leak-detection-threshold: 30000
      # Removed data-source-properties as they are now in the JDBC URL

  liquibase:
    enabled: false # Disable Liquibase for ClickHouse compatibility
    # Removed change-log, contexts, default-schema as Liquibase is disabled

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "prometheus", "info"]
  endpoint:
    health:
      show-details: always

logging:
  level:
    liquibase: WARN # Set to WARN to suppress unnecessary Liquibase messages
    com.clickhouse: INFO
    com.zaxxer.hikari: INFO
