server:
  port: 8080

spring:
  application:
    name: backendvault

  datasource:
    url: jdbc:clickhouse://localhost:8123/trading_db?autoCommit=true&compress=true&tcpKeepAlive=true
    username: ${DB_USERNAME:default}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 250
      validation-timeout: 250
      leak-detection-threshold: 30000
      data-source-properties:
        socket_timeout: 300000
        max_execution_time: 60

  jpa:
    hibernate:
      ddl-auto: none   # ❌ don't let Hibernate auto-DDL, let Liquibase handle schema
    properties:
      hibernate.dialect: org.hibernate.dialect.ClickHouseDialect
      hibernate.show_sql: false
      hibernate.format_sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/master.xml
    contexts: dev
    default-schema: trading

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "prometheus", "info"]
  endpoint:
    health:
      show-details: always

logging:
  level:
    liquibase: INFO
    com.clickhouse: INFO
    com.zaxxer.hikari: INFO
